### ISSUE TITLE
Compiler errors prevent games from being reset

### ISSUE THREAD

**Issue by Rohansi** [Facepunch/arcade-issues#4]
When a game fails to compile in BBDK you can't use the reset button to recompile it. You need to reselect it from the games list to compile it again.

To reproduce:

1. Load a game that will fail to compile (leave out a semicolon or something).
2. Fix the issue that is preventing it from compiling.
3. Press the reset button and it will just change the background color.

**Comment by Metapyziks** [comment]
Fixed, will be distributed in a new BBDK release soon.

Thank you for reporting!
