### ISSUE TITLE
BBDK 0.1.5490.28067 (Linux - Ubuntu) - Null Pointer Exception when loading games

### ISSUE THREAD

**Issue by Rybadour** [Facepunch/arcade-issues#9]
When loading any game except "Mazing" I get a "Null Pointer Exception" on the console and the sounds stops playing but the Mazing game still runs.

**Comment by Metapyziks** [comment]
I'm unable to reproduce this on Arch Linux, so it looks like this may be Ubuntu specific. Could you upload the contents of "~/.config/unity3d/Facepunch Studios/DevKit/Player.log"?

Thank you for reporting!

**Comment by Rybadour** [comment]
Here you go: http://hastebin.com/oyawaropam.coffee

Other things that happened:
- The next previous version worked like a charm.
- In the broke version I was somehow able to load 3d Shooter but only if I do it first (after the mazing game loads)

**Comment by Metapyziks** [comment]
Thanks, it looks like the problem may be that it can't find the Mono C# compiler. However, could you try out the following cases just to be sure, to see which ones give you an error:

1. Load a pre-packaged game first in the latest version (a game with a PKG icon)
2. Load a game from source first in the latest version (a game with a C# icon)
3. Load a game from source first in the previous version (a game with a C# icon)

**Comment by Rybadour** [comment]
1. It works, not sure how I missed that :p 
2. C# files cause the bad behaviour
3. I just noticed this as well while playing around with the tutorial. I can't load any C# games. But it doesn't cause the whole DevKit to become unusable.

**Comment by Metapyziks** [comment]
That helps a lot, thank you!

Firstly, this is our fault for not mentioning anywhere that you will need to install [Mono](http://www.mono-project.com/download) to compile games on OSX / Linux, which I'll fix now.

Secondly, the BBDK breaking after attempting to compile a game without Mono is definitely a bug, so we'll fix that too.

Thanks again for reporting this issue!

**Comment by Rybadour** [comment]
No problem thanks for the reply. I'll install Mono and see how that works out.
